baseURL = "https://gypsy-lulu.com"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "Gypsy Lulu | Travel Blog"
theme = "blogge-hugo-theme"
enableEmoji = true

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "Cuisine"
    url= "cuisine"
    weight= 2
  [[menu.main]]
    name = "Experiences"
    url= "experience"
    weight= 3
  # removed until we add the first article for perspective
  # [[menu.main]]
  #   name = "Perspective"
  #   url= ""
  #   weight= 4  
  [[menu.main]]
    name = "Places"
    url= "place"
    weight= 5
  [[menu.main]]
    name = "Skills"
    url= "skill"
    weight= 6
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 7
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 8


[params]
  summarylength = 80
  logo = "images/logo.png"
  author = "Luana & Matthew"
  authorThumb = "images/matt-and-lulu.png"
  authorAddress = "Somewhere in Thailand"
  authorPhone = "+66 6-4110-1052"
  instaUsername = "GypsyLulu"
  facebookUsername = "mary_astor"
  twitterUsername = "mary_astor"
  linkedinUsername = "matthew-henderson-986374bb"
  youtubeUsername = "UCI-dfBogFVLoaxbo5hxe_og"
  blogTitle = "Articles"
  blogSubTitle = "View the latest posts on Gypsy Lulu"
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  custom_css = [
    "css/recipe_box.css"
  ]

[taxonomies]
  tag = "tags"


