backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow # Allows drafting, reviewing and approving articles
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads